BB_SHOW_TEXT_BOX
    jsr BB_DRAW_BOX

    ; center white text
    jsr TEXT_CENTER_STRING
    lda #7
    sta TEXT_Y
    lda #WHITE
    sta TEXT_COLOR
    jsr TEXT_DRAW_STRING

    ; return text
    lda #<BB_TEXT_RETURN
    sta TEXT_STRING_PTR
    lda #>BB_TEXT_RETURN
    sta TEXT_STRING_PTR+1
    jsr TEXT_CENTER_STRING
    lda #10
    sta TEXT_Y
    jsr TEXT_DRAW_STRING

    jsr TEXT_WAIT_FOR_ENTER_SPACE
    rts

BB_SHOW_OPTIONS_BOX
    rts
BB_SHOW_TEXT_ENTRY_BOX
    jsr BB_DRAW_BOX

    ; center white text
    jsr TEXT_CENTER_STRING
    lda #7
    sta TEXT_Y
    lda #WHITE
    sta TEXT_COLOR
    jsr TEXT_DRAW_STRING

    jsr BB_TEXT_ENTRY
    rts

BB_DRAW_BOX
    ; text always white
    ldy #WHITE

    ; top row border
    ldx #0
-
    lda #119 ; high hoz bar
    sta BB_TEXT_BOX_TOP_BORDER_ROW, x
    lda #WHITE
    sta BB_TEXT_BOX_TOP_BORDER_ROW_COL, x
    inx
    cpx #40
    bne -
    ; top left
    lda #79
    sta BB_TEXT_BOX_TOP_BORDER_ROW
    ; top right
    lda #80
    sta BB_TEXT_BOX_TOP_BORDER_ROW+39

    ; text 1 blank
    ldx #0
-
    lda #' '
    sta BB_TEXT_BOX_TEXT_ROW_1, x
    lda #WHITE
    sta BB_TEXT_BOX_TEXT_ROW_COL_1, x
    inx
    cpx #40
    bne -
    ; left
    lda #101
    sta BB_TEXT_BOX_TEXT_ROW_1
    ; right
    lda #103
    sta BB_TEXT_BOX_TEXT_ROW_1+39

    ; text gap blank
    ldx #0
-
    lda #' '
    sta BB_TEXT_BOX_TEXT_ROW_GAP, x
    lda #WHITE
    sta BB_TEXT_BOX_TEXT_ROW_COL_GAP, x
    inx
    cpx #40
    bne -
    ; left
    lda #101
    sta BB_TEXT_BOX_TEXT_ROW_GAP
    ; right
    lda #103
    sta BB_TEXT_BOX_TEXT_ROW_GAP+39

    ; text 2 blank
    ldx #0
-
    lda #' '
    sta BB_TEXT_BOX_TEXT_ROW_2, x
    lda #WHITE
    sta BB_TEXT_BOX_TEXT_ROW_COL_2, x
    inx
    cpx #40
    bne -
    ; left
    lda #101
    sta BB_TEXT_BOX_TEXT_ROW_2
    ; right
    lda #103
    sta BB_TEXT_BOX_TEXT_ROW_2+39

    ; bot row border
    ldx #0
-
    lda #111 ; low hoz bar
    sta BB_TEXT_BOX_BOT_BORDER_ROW, x
    lda #WHITE
    sta BB_TEXT_BOX_BOT_BORDER_ROW_COL, x
    inx
    cpx #40
    bne -
    ; bot left
    lda #76
    sta BB_TEXT_BOX_BOT_BORDER_ROW
    ; bot right
    lda #122
    sta BB_TEXT_BOX_BOT_BORDER_ROW+39

    rts

BB_JUMP_SHOW
    ; turn on blue box mode
    lda #1
    sta RASTER_BLUE_BOX_STATUS

    ; where string
    lda #<BB_JUMP_WHERE
    sta TEXT_STRING_PTR
    lda #>BB_JUMP_WHERE
    sta TEXT_STRING_PTR+1

    jsr BB_SHOW_TEXT_ENTRY_BOX

    ; turn off blue box mode
    lda #0
    sta RASTER_BLUE_BOX_STATUS

    ; jump effect
    lda #BLACK
    sta SCREEN_SYSTEM_COLOR_1
    sta SCREEN_SYSTEM_COLOR_2
    sta SCREEN_SYSTEM_COLOR_3
    sta SCREEN_SYSTEM_COLOR_4
    jsr STARS_FILL_SCREEN
    jsr STARS_FILL_SCREEN
    jsr STARS_FILL_SCREEN
    jsr STARS_FILL_SCREEN

    ; save system name
    ldx #0
-
    lda BB_TEXT_ENTRY_BUFFER, x
    sta SCREEN_SYSTEM_NAME_BUFFER, x
    inx
    cpx #BB_MAX_CHARS
    bne -
    
    jmp SCREEN_SYSTEM_SHOW

BB_JUMP_WHERE
    !scr "jump to which system?", 0

BB_SHIP_NAME_SHOW
    ; turn on blue box mode
    lda #1
    sta RASTER_BLUE_BOX_STATUS

    ; where string
    lda #<BB_SHIP_NAME
    sta TEXT_STRING_PTR
    lda #>BB_SHIP_NAME
    sta TEXT_STRING_PTR+1

    jsr BB_SHOW_TEXT_ENTRY_BOX

    ; turn off blue box mode
    lda #0
    sta RASTER_BLUE_BOX_STATUS

    ; jump effect
    lda #BLACK
    sta SCREEN_SYSTEM_COLOR_1
    sta SCREEN_SYSTEM_COLOR_2
    sta SCREEN_SYSTEM_COLOR_3
    sta SCREEN_SYSTEM_COLOR_4
    jsr STARS_FILL_SCREEN
    jsr STARS_FILL_SCREEN
    jsr STARS_FILL_SCREEN
    jsr STARS_FILL_SCREEN

    ; save ship name
    ldx #0
-
    lda BB_TEXT_ENTRY_BUFFER, x
    sta SHIP_NAME_BUFFER, x
    inx
    cpx #BB_MAX_CHARS
    bne -

    jsr SHIP_GEN_FROM_NAME

    ; save system name
    ldx #0
-
    lda SHIP_HOME_BUFFER, x
    sta SCREEN_SYSTEM_NAME_BUFFER, x
    inx
    cpx #BB_MAX_CHARS
    bne -

    jmp SCREEN_SYSTEM_SHOW

BB_SHIP_NAME
    !scr "ship, what is your name?", 0


BB_TEXT_BOX_TOP_BORDER_ROW      = SCREEN_RAM + (6 * 40)
BB_TEXT_BOX_TEXT_ROW_1          = BB_TEXT_BOX_TOP_BORDER_ROW + 40
BB_TEXT_BOX_TEXT_ROW_GAP        = BB_TEXT_BOX_TEXT_ROW_1 + 40
BB_TEXT_BOX_TEXT_ROW_2          = BB_TEXT_BOX_TEXT_ROW_GAP + 40
BB_TEXT_BOX_BOT_BORDER_ROW      = BB_TEXT_BOX_TEXT_ROW_2 + 40

BB_TEXT_BOX_TOP_BORDER_ROW_COL  = COLOR_RAM + (6 * 40)
BB_TEXT_BOX_TEXT_ROW_COL_1      = BB_TEXT_BOX_TOP_BORDER_ROW_COL + 40
BB_TEXT_BOX_TEXT_ROW_COL_GAP    = BB_TEXT_BOX_TEXT_ROW_COL_1 + 40
BB_TEXT_BOX_TEXT_ROW_COL_2      = BB_TEXT_BOX_TEXT_ROW_COL_GAP + 40
BB_TEXT_BOX_BOT_BORDER_ROW_COL  = BB_TEXT_BOX_TEXT_ROW_COL_2 + 40


BB_TEXT_RETURN
    !scr "> return <", 0


; keyboard reading routines initially generated by Gemini AI
; I've already learned how to read the keys, so I considered this busy work
; but turns out I hadn't thought of doing the matrix like this, so I learned something new!

BB_TEXT_ENTRY
    ; blank entry area
    lda #<BB_TEXT_BLANK
    sta TEXT_STRING_PTR
    lda #>BB_TEXT_BLANK
    sta TEXT_STRING_PTR+1
    jsr TEXT_CENTER_STRING
    lda #9
    sta TEXT_Y
    jsr TEXT_DRAW_STRING

    lda #0
    sta BB_TEXT_ENTRY_BUFFER    ; clear buffer (null start)
    sta BB_CHAR_COUNT           ; reset size
    

.bb_text_entry_loop
    jsr BB_SCAN_MATRIX  ; Scan the hardware
    lda BB_KEY_PRESSED
    beq .no_key         ; If A = 0, no key is being pressed right now

    ; --- DEBOUNCE CHECK ---
    cmp BB_LAST_KEY_PRESSED  ; Is this the same key as last frame?
    beq .finish                 ; Yes? Skip it (player is holding the key down)
    sta BB_LAST_KEY_PRESSED        ; No? Store it as the new held key

    ; --- PROCESS SPECIAL KEYS ---
    cmp #$fe            ; Custom code for RETURN (defined in our table)
    beq .text_entry_done

    cmp #$ff            ; Custom code for DELETE (defined in our table)
    beq .handle_delete

    ; --- PROCESS STANDARD TEXT ---
    ldx BB_CHAR_COUNT
    cpx #BB_MAX_CHARS
    bcs .finish         ; Name full, ignore text input

    ; is it a space?
    cmp #$20
    beq .handle_space

.handle_add_character
    sta BB_TEXT_ENTRY_BUFFER,x   ; Save raw screen code to buffer
    inx 
    lda #0
    sta BB_TEXT_ENTRY_BUFFER,x   ; save null terminator
    inc BB_CHAR_COUNT
    jmp .update_text

.update_text:
    ; blank entry area
    lda #<BB_TEXT_BLANK
    sta TEXT_STRING_PTR
    lda #>BB_TEXT_BLANK
    sta TEXT_STRING_PTR+1
    jsr TEXT_CENTER_STRING
    lda #9
    sta TEXT_Y
    jsr TEXT_DRAW_STRING

    ; show updated entry text
    lda #<BB_TEXT_ENTRY_BUFFER
    sta TEXT_STRING_PTR
    lda #>BB_TEXT_ENTRY_BUFFER
    sta TEXT_STRING_PTR+1
    jsr TEXT_CENTER_STRING
    lda #9
    sta TEXT_Y
    jsr TEXT_DRAW_STRING
    jmp .finish

.no_key:
    lda #0              ; No keys are pressed, so reset debounce tracker
    sta BB_LAST_KEY_PRESSED

.finish:
    jmp .bb_text_entry_loop

.text_entry_done:
    ; check it's not empty...
    lda BB_CHAR_COUNT
    beq .bb_text_entry_loop

    ; check final char isn't a space
    ldx BB_CHAR_COUNT
    dex
    lda BB_TEXT_ENTRY_BUFFER,x
    cmp #$20
    bne +
    
    ; remove final space
    lda #0
    sta BB_TEXT_ENTRY_BUFFER,x
    dec BB_CHAR_COUNT
+
    rts

.handle_space:
    cpx #0
    beq .finish                 ; first character can't be space 

    ; check not double space 
    dex
    ldy BB_TEXT_ENTRY_BUFFER,x  ; previous character
    inx
    cpy #$20
    beq .finish                 ; no double spaces


    jmp .handle_add_character

.handle_delete:
    ldx BB_CHAR_COUNT
    beq .finish         ; Nothing to delete
    dec BB_CHAR_COUNT
    ldx BB_CHAR_COUNT
    lda #0              ; null terminator
    sta BB_TEXT_ENTRY_BUFFER,x   ; Clear from buffer
    jmp .update_text


BB_SCAN_MATRIX
    lda #0              ; Clear result
    sta BB_KEY_PRESSED
    
    lda #$ff
    sta $dc02           ; Set CIA 1 Port A to all outputs
    lda #$00
    sta $dc03           ; Set CIA 1 Port B to all inputs

    ldx #0              ; X will count our 8 rows (0-7)
    lda #$fe            ; Start by pulling Row 0 low (%11111110)

.row_loop:
    sta CIA1_PRA        ; Select row
    nop                 ; Tiny hardware settling delay
    nop
    
    ldy CIA1_PRB        ; Read columns
    cpy #$ff            ; Is any bit 0? ($FF means all 1s, no keys pressed)
    bne .find_column    ; Found a key press! Go decode it

    sec
    rol                 ; Shift the 0 to the next row (e.g., %11111101)
    inx
    cpx #8
    bne .row_loop       ; Loop until all 8 rows are scanned
    rts                 ; No keys found at all, return

.find_column:
    ; Y contains the active low column data (e.g., %11111011)
    ; We need to figure out which bit index (0-7) is 0
    sty $fe             ; Temporary storage for column bits
    ldy #0
.col_loop:
    lsr $fe             ; Shift lowest bit into Carry
    bcc .decode         ; If Carry is 0, we found the column!
    iny
    cpy #8
    bne .col_loop
    rts

.decode:
    ; Row index is in X, Column index is in Y
    ; Calculate offset: (Row * 8) + Column
    txa
    asl
    asl
    asl                 ; A = Row * 8
    sty $fe
    clc
    adc $fe             ; A = (Row * 8) + Column
    tax                 ; Move index into X

    lda BB_KEY_MATRIX,x  ; Look up screen code from layout table
    sta BB_KEY_PRESSED     ; Store it
    rts



; Matrix lookup table mapping hardware indices directly to C64 Screen Codes
BB_KEY_MATRIX
;          Col 0  Col 1  Col 2  Col 3  Col 4  Col 5  Col 6  Col 7
;          -------------------------------------------------------
; Row 0:   DEL    RET    CRSR   F7     F1     F3     F5     CRSR
!byte      $ff,   $fe,   $00,   $00,   $00,   $00,   $00,   $00
; Row 1:   3      W      A      4      Z      S      E      SHIFT
!byte      $33,   $17,   $01,   $34,   $1a,   $13,   $05,   $00
; Row 2:   5      R      D      6      C      F      T      X
!byte      $35,   $12,   $04,   $36,   $03,   $06,   $14,   $18
; Row 3:   7      Y      G      8      B      H      U      V
!byte      $37,   $19,   $07,   $38,   $02,   $08,   $15,   $16
; Row 4:   9      I      J      0      M      K      O      N
!byte      $39,   $09,   $0a,   $30,   $0d,   $0b,   $0f,   $0e
; Row 5:   +      P      L      -      .      :      @      ,
!byte      $2b,   $10,   $0c,   $2d,   $2e,   $00,   $00,   $2c
; Row 6:   pound  *      ;      HOME   SHIFT  =      ^      /
!byte      $23,   $2a,   $3b,   $00,   $00,   $3d,   $00,   $2e
; Row 7:   1      left   CTRL   2      SPACE  C=     Q      STOP
!byte      $31,   $00,   $00,   $32,   $20,   $00,   $11,   $00

BB_MAX_CHARS = 20
BB_TEXT_ENTRY_BUFFER
    !fill BB_MAX_CHARS+1, 0
BB_KEY_PRESSED
    !byte 0
BB_LAST_KEY_PRESSED
    !byte 0    
BB_CHAR_COUNT
    !byte 0
BB_TEXT_BLANK
    !scr ">                      <", 0
