MESSAGE_TO_LABEL
    !scr "to:", 0
MESSAGE_MESSAGE_LABEL
    !scr "message:", 0

MESSAGE_SHOW_TOP = SCREEN_RAM
MESSAGE_SHOW_TOP_COL = COLOR_RAM

MESSAGE_LEFT_BORDER
    !fill 14, 101
    !byte 0

MESSAGE_RIGHT_BORDER
    !fill 14, 103
    !byte 0

MESSAGE_SEND_MODE
    !byte 0

MESSAGE_SYSTEM_COLOR_TOP_SPACE_BORDER 
    !byte 0
MESSAGE_SYSTEM_COLOR_TEXT_BG
    !byte 0
MESSAGE_SYSTEM_COLOR_TEXT_BORDER
    !byte 0
MESSAGE_SYSTEM_COLOR_BOTTOM_BORDER  
    !byte 0
