DIPLOMAT_PASSENGER_LABEL
    !scr "passenger", 0
DIPLOMAT_NONE_LABEL
    !scr "< none >", 0
DIPLOMAT_FULL_LABEL
    !scr "< cabin full >", 0
DIPLOMAT_DIPLOMAT_LABEL
    !scr "diplomat", 0
DIPLOMAT_COMMS_LABEL
    !scr "comms", 0
DIPLOMAT_CALL_LABEL
    !byte 131
    !scr "all ship", 0
DIPLOMAT_SEND_LABEL
    !byte 147
    !scr "end message", 0
DIPLOMAT_READ_LABEL
    !byte 146
    !scr "ead message", 0
DIPLOMAT_DEST_LABEL
    !scr "destination", 0

DIPLOMAT_BUFFER
    !fill BB_MAX_CHARS+1, 0

DIPLOMAT_PASSENGER_BUFFER
    !fill BB_MAX_CHARS+1, 0
DIPLOMAT_PASSENGER_DEST_BUFFER
    !fill BB_MAX_CHARS+1, 0

DIPLOMAT_HAS_PASSENGER
    !byte 0
DIPLOMAT_PASSENGER_SEED_W0
    !word 0
DIPLOMAT_PASSENGER_SEED_W1
    !word 0
DIPLOMAT_PASSENGER_SEED_W2
    !word 0

DIPLOMAT_LOGO_TL_CHAR
    !byte 0
DIPLOMAT_LOGO_TR_CHAR
    !byte 0
DIPLOMAT_LOGO_BL_CHAR
    !byte 0
DIPLOMAT_LOGO_BR_CHAR
    !byte 0
DIPLOMAT_LOGO_TL_COL
    !byte 0
DIPLOMAT_LOGO_TR_COL
    !byte 0
DIPLOMAT_LOGO_BL_COL
    !byte 0
DIPLOMAT_LOGO_BR_COL
    !byte 0
DIPLOMAT_LOGO_BORDER_COLOR
    !byte 0
